version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: shopdb
    environment:
      MYSQL_DATABASE: "shopdb"
      MYSQL_PASSWORD: "myamazingpassword"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: